// Danfo Craze: Africa quiz bank.
// q = question, o = options, a = index of the right option, f = short fact shown after answering.
// Keep facts checkable; word tricky ones precisely (e.g. "sub-Saharan", "mainland").
window.DC_QUIZ = [
  { q: 'What is the largest country in Africa by land area?', o: ['Nigeria', 'Algeria', 'DR Congo', 'Sudan'], a: 1, f: 'Algeria has been Africa\'s largest country since South Sudan split from Sudan in 2011.' },
  { q: 'How many African countries are members of the United Nations?', o: ['48', '50', '54', '60'], a: 2, f: 'Africa has 54 UN member states. The African Union has 55 members because it also includes the Sahrawi Republic.' },
  { q: 'Which was the first African country south of the Sahara Desert (sub-Saharan Africa) to gain independence from colonial rule?', o: ['Nigeria', 'Kenya', 'Ghana', 'Senegal'], a: 2, f: 'Ghana became independent from Britain on 6 March 1957, led by Kwame Nkrumah. (Egypt, Libya, Sudan, Morocco and Tunisia, north of the Sahara, were earlier.)' },
  { q: 'Which is the most populous country in Africa?', o: ['Nigeria', 'Egypt', 'Ethiopia', 'DR Congo'], a: 0, f: 'Nigeria has the largest population in Africa, over 200 million people.' },
  { q: 'What is the longest river in Africa?', o: ['Congo', 'Niger', 'Zambezi', 'Nile'], a: 3, f: 'The Nile flows about 6,650 km north into the Mediterranean Sea.' },
  { q: 'What is the highest mountain in Africa?', o: ['Mount Kenya', 'Kilimanjaro', 'Atlas Mountains', 'Mount Cameroon'], a: 1, f: 'Mount Kilimanjaro in Tanzania rises about 5,895 metres.' },
  { q: 'What is the largest desert in Africa?', o: ['Kalahari', 'Namib', 'Sahara', 'Danakil'], a: 2, f: 'The Sahara is the largest hot desert in the world.' },
  { q: 'What is the capital of Nigeria?', o: ['Lagos', 'Abuja', 'Kano', 'Ibadan'], a: 1, f: 'Abuja replaced Lagos as Nigeria\'s capital in 1991.' },
  { q: 'What is the capital of Kenya?', o: ['Mombasa', 'Kisumu', 'Nairobi', 'Nakuru'], a: 2, f: 'Nairobi has a national park with lions and giraffes right next to the city.' },
  { q: 'What is the capital of Ghana?', o: ['Kumasi', 'Accra', 'Tamale', 'Cape Coast'], a: 1, f: 'Accra sits on Ghana\'s Atlantic coast.' },
  { q: 'How many capital cities does South Africa have?', o: ['One', 'Two', 'Three', 'Four'], a: 2, f: 'Pretoria (government), Cape Town (parliament) and Bloemfontein (courts).' },
  { q: 'What is the capital of Egypt?', o: ['Alexandria', 'Cairo', 'Luxor', 'Giza'], a: 1, f: 'Cairo sits on the River Nile, close to the Pyramids of Giza.' },
  { q: 'Which city hosts the headquarters of the African Union?', o: ['Addis Ababa', 'Nairobi', 'Abuja', 'Johannesburg'], a: 0, f: 'The African Union is headquartered in Addis Ababa, Ethiopia.' },
  { q: 'Which African country was never colonised, apart from a short Italian occupation from 1936 to 1941?', o: ['Kenya', 'Ethiopia', 'Ghana', 'Morocco'], a: 1, f: 'Ethiopia defeated Italy at the Battle of Adwa in 1896.' },
  { q: 'Nelson Mandela became the first democratically elected president of which country?', o: ['Zimbabwe', 'Namibia', 'South Africa', 'Botswana'], a: 2, f: 'Mandela was president of South Africa from 1994 to 1999, after 27 years in prison.' },
  { q: 'What is the largest lake in Africa?', o: ['Lake Tanganyika', 'Lake Chad', 'Lake Malawi', 'Lake Victoria'], a: 3, f: 'Lake Victoria is shared by Uganda, Kenya and Tanzania.' },
  { q: 'Victoria Falls lies on the border of which two countries?', o: ['Zambia and Zimbabwe', 'Kenya and Uganda', 'Ghana and Togo', 'Egypt and Sudan'], a: 0, f: 'Locally it is called Mosi-oa-Tunya, "the smoke that thunders".' },
  { q: 'What is the currency of Nigeria?', o: ['Cedi', 'Naira', 'Rand', 'Shilling'], a: 1, f: 'The naira (₦) replaced the Nigerian pound in 1973.' },
  { q: 'What is the currency of Ghana?', o: ['Cedi', 'Naira', 'Dalasi', 'Kwacha'], a: 0, f: 'The Ghanaian cedi is named after a cowry shell, once used as money.' },
  { q: 'What is the currency of South Africa?', o: ['Pula', 'Rand', 'Birr', 'Naira'], a: 1, f: 'The rand is named after the Witwatersrand, the gold-rich ridge near Johannesburg.' },
  { q: 'In which country is the Great Pyramid of Giza?', o: ['Sudan', 'Libya', 'Egypt', 'Morocco'], a: 2, f: 'It is the oldest of the Seven Wonders of the Ancient World still standing.' },
  { q: 'Which country is called the "Land of a Thousand Hills"?', o: ['Rwanda', 'Lesotho', 'Kenya', 'Malawi'], a: 0, f: 'Rwanda\'s capital Kigali is known as one of Africa\'s cleanest cities.' },
  { q: 'Mount Kilimanjaro is in which country?', o: ['Kenya', 'Uganda', 'Tanzania', 'Ethiopia'], a: 2, f: 'Kilimanjaro is a dormant volcano with snow near the equator.' },
  { q: 'Which ocean lies to the east of Africa?', o: ['Atlantic', 'Pacific', 'Indian', 'Arctic'], a: 2, f: 'The Indian Ocean washes the coasts from Somalia down to South Africa.' },
  { q: 'Which sea separates Africa from Europe?', o: ['Red Sea', 'Mediterranean Sea', 'Black Sea', 'Arabian Sea'], a: 1, f: 'At the Strait of Gibraltar, Africa and Europe are only about 14 km apart.' },
  { q: 'Which island country off Africa\'s south-east coast is famous for lemurs?', o: ['Mauritius', 'Madagascar', 'Seychelles', 'Comoros'], a: 1, f: 'Lemurs live naturally only on Madagascar.' },
  { q: 'Who was the first Black African to win the Nobel Prize in Literature?', o: ['Chinua Achebe', 'Wole Soyinka', 'Ngũgĩ wa Thiong\'o', 'Ama Ata Aidoo'], a: 1, f: 'Nigerian writer Wole Soyinka won it in 1986.' },
  { q: 'Who wrote the novel "Things Fall Apart"?', o: ['Chinua Achebe', 'Wole Soyinka', 'Chimamanda Adichie', 'Ben Okri'], a: 0, f: 'Published in 1958, it is one of the most widely read African novels.' },
  { q: 'Which Kenyan was the first African woman to win the Nobel Peace Prize?', o: ['Wangari Maathai', 'Graça Machel', 'Leymah Gbowee', 'Winnie Mandela'], a: 0, f: 'Wangari Maathai won in 2004 for her Green Belt Movement, which planted millions of trees.' },
  { q: 'Who was the first woman elected head of state in Africa?', o: ['Joyce Banda', 'Ellen Johnson Sirleaf', 'Sahle-Work Zewde', 'Samia Suluhu Hassan'], a: 1, f: 'Ellen Johnson Sirleaf was elected president of Liberia in 2005.' },
  { q: 'Which country\'s flag has a black star in the middle?', o: ['Ghana', 'Senegal', 'Cameroon', 'Morocco'], a: 0, f: 'The Black Star stands for African freedom. Ghana\'s football team is the Black Stars.' },
  { q: 'What colours are on the flag of Nigeria?', o: ['Green and white', 'Red and green', 'Green, yellow and red', 'Blue and white'], a: 0, f: 'Green for the land, white for peace.' },
  { q: 'In which year did Nigeria gain independence?', o: ['1957', '1960', '1963', '1970'], a: 1, f: 'Nigeria became independent on 1 October 1960.' },
  { q: 'In which year did Kenya gain independence?', o: ['1957', '1960', '1963', '1975'], a: 2, f: 'Kenya became independent on 12 December 1963.' },
  { q: 'In which year did South Africa hold its first democratic elections?', o: ['1980', '1990', '1994', '2000'], a: 2, f: 'The April 1994 elections ended apartheid rule.' },
  { q: 'What is the fastest land animal, found in Africa?', o: ['Lion', 'Cheetah', 'Zebra', 'Antelope'], a: 1, f: 'A cheetah can sprint at around 100 km/h.' },
  { q: 'What is the tallest animal in the world?', o: ['Elephant', 'Camel', 'Giraffe', 'Ostrich'], a: 2, f: 'Giraffes can grow over 5 metres tall.' },
  { q: 'What is the largest land animal in the world?', o: ['Hippo', 'Rhino', 'African elephant', 'Giraffe'], a: 2, f: 'An adult African bush elephant can weigh over 6 tonnes.' },
  { q: 'Who pioneered Afrobeat music in the 1970s?', o: ['Fela Kuti', 'King Sunny Adé', 'Miriam Makeba', 'Youssou N\'Dour'], a: 0, f: 'Fela Anikulapo Kuti mixed highlife, jazz and funk into Afrobeat in Lagos.' },
  { q: 'Which country has more ancient pyramids than any other?', o: ['Egypt', 'Sudan', 'Mexico', 'Ethiopia'], a: 1, f: 'Sudan has over 200 Nubian pyramids, more than Egypt.' },
  { q: 'Timbuktu, a famous centre of learning, is in which country?', o: ['Niger', 'Mali', 'Chad', 'Mauritania'], a: 1, f: 'Its ancient libraries hold hundreds of thousands of manuscripts.' },
  { q: 'Mansa Musa, one of the richest people in history, ruled which empire?', o: ['Mali Empire', 'Songhai Empire', 'Benin Kingdom', 'Aksum'], a: 0, f: 'His 1324 journey to Mecca was so lavish it was talked about for centuries.' },
  { q: 'The stone city of Great Zimbabwe is in which country?', o: ['Zambia', 'Zimbabwe', 'Mozambique', 'Botswana'], a: 1, f: 'Zimbabwe, meaning "houses of stone", is named after it.' },
  { q: 'The Suez Canal is in which country?', o: ['Egypt', 'Sudan', 'Libya', 'Tunisia'], a: 0, f: 'It links the Mediterranean Sea with the Red Sea.' },
  { q: 'What is the capital of Senegal?', o: ['Dakar', 'Bamako', 'Conakry', 'Banjul'], a: 0, f: 'Dakar is the westernmost city on mainland Africa.' },
  { q: 'What is the capital of Rwanda?', o: ['Kampala', 'Kigali', 'Bujumbura', 'Goma'], a: 1, f: 'Kigali banned plastic bags back in 2008.' },
  { q: 'What is the capital of DR Congo?', o: ['Brazzaville', 'Lubumbashi', 'Kinshasa', 'Goma'], a: 2, f: 'Kinshasa faces Brazzaville across the Congo River. They are the closest pair of capital cities in the world.' },
  { q: 'What is the capital of Morocco?', o: ['Casablanca', 'Marrakech', 'Rabat', 'Fes'], a: 2, f: 'Casablanca is Morocco\'s biggest city, but Rabat is the capital.' },
  { q: 'What is the official capital of Tanzania?', o: ['Dar es Salaam', 'Dodoma', 'Arusha', 'Zanzibar City'], a: 1, f: 'Dar es Salaam is the biggest city, but the capital is Dodoma.' },
  { q: 'What is the official capital of Côte d\'Ivoire?', o: ['Abidjan', 'Yamoussoukro', 'Bouaké', 'San-Pédro'], a: 1, f: 'Abidjan is the economic hub; Yamoussoukro is the official capital.' },
  { q: 'Which African country hosted the 2010 FIFA World Cup?', o: ['Nigeria', 'Egypt', 'South Africa', 'Morocco'], a: 2, f: 'It was the first World Cup held in Africa.' },
  { q: 'Which was the first African team to reach a men\'s FIFA World Cup semi-final?', o: ['Cameroon', 'Senegal', 'Ghana', 'Morocco'], a: 3, f: 'Morocco reached the semi-finals at Qatar 2022.' },
  { q: 'The Blue Nile starts at which lake?', o: ['Lake Tana', 'Lake Victoria', 'Lake Turkana', 'Lake Kivu'], a: 0, f: 'Lake Tana is in the highlands of Ethiopia.' },
  { q: 'In which city do the Blue Nile and White Nile meet?', o: ['Cairo', 'Khartoum', 'Juba', 'Kampala'], a: 1, f: 'They join at Khartoum, the capital of Sudan.' },
  { q: 'What is the smallest country on mainland Africa?', o: ['Rwanda', 'Eswatini', 'The Gambia', 'Djibouti'], a: 2, f: 'The Gambia is a thin strip of land along the Gambia River, surrounded by Senegal.' },
  { q: 'What is the smallest country in Africa, including islands?', o: ['Seychelles', 'Comoros', 'São Tomé and Príncipe', 'Mauritius'], a: 0, f: 'Seychelles is a group of 115 islands in the Indian Ocean.' },
  { q: 'The Namib, one of the oldest deserts on Earth, is mostly in which country?', o: ['Namibia', 'Botswana', 'Angola', 'South Africa'], a: 0, f: 'Namibia is named after the Namib Desert.' },
  { q: 'The okapi, a relative of the giraffe, lives wild only in which country?', o: ['Kenya', 'DR Congo', 'Uganda', 'Cameroon'], a: 1, f: 'The okapi has zebra-like stripes on its legs.' },
  { q: 'The Serengeti, famous for its great wildebeest migration, is mainly in which country?', o: ['Tanzania', 'Nigeria', 'Ghana', 'Egypt'], a: 0, f: 'Each year over a million wildebeest move between the Serengeti and Kenya\'s Maasai Mara.' },
  { q: 'Nollywood is the film industry of which country?', o: ['Ghana', 'Kenya', 'Nigeria', 'South Africa'], a: 2, f: 'Nollywood makes more films each year than Hollywood.' },
  { q: 'Which Nigerian artist won the Grammy for Best Global Music Album in 2021?', o: ['Wizkid', 'Burna Boy', 'Davido', 'Tiwa Savage'], a: 1, f: 'Burna Boy won with his album "Twice as Tall".' },
  { q: 'Kente cloth comes from which country?', o: ['Ghana', 'Kenya', 'Egypt', 'Zambia'], a: 0, f: 'Kente is woven by the Asante and Ewe peoples in bright strips.' },
  { q: 'What was the writing system of ancient Egypt called?', o: ['Cuneiform', 'Hieroglyphs', 'Ge\'ez', 'Tifinagh'], a: 1, f: 'Hieroglyphs used pictures to represent sounds and ideas.' },
  { q: 'The Cape of Good Hope is in which country?', o: ['Namibia', 'South Africa', 'Mozambique', 'Madagascar'], a: 1, f: 'It is near Cape Town, at the south-western tip of Africa.' },
  { q: 'How many countries border Lake Chad?', o: ['Two', 'Three', 'Four', 'Six'], a: 2, f: 'Nigeria, Niger, Chad and Cameroon all border Lake Chad.' },
  { q: 'Which sea lies between north-east Africa and Arabia?', o: ['Red Sea', 'Dead Sea', 'Caspian Sea', 'Black Sea'], a: 0, f: 'The Red Sea connects to the Mediterranean through the Suez Canal.' },
  { q: 'Mountain gorillas can be seen in the wild in which of these countries?', o: ['Egypt', 'Senegal', 'Rwanda', 'Morocco'], a: 2, f: 'They live in the Virunga mountains of Rwanda, Uganda and DR Congo.' },
  { q: 'The Maasai Mara reserve is in which country?', o: ['Kenya', 'Nigeria', 'Ghana', 'Algeria'], a: 0, f: 'The Maasai people are known for their red shukas and jumping dance.' },
  { q: 'Which language is widely spoken across East Africa, including Kenya and Tanzania?', o: ['Hausa', 'Swahili', 'Zulu', 'Amharic'], a: 1, f: '"Karibu" means "welcome" in Swahili.' },
  { q: 'Jollof rice is a favourite dish of which region?', o: ['North Africa', 'West Africa', 'Southern Africa', 'Horn of Africa'], a: 1, f: 'Nigeria, Ghana and Senegal all argue about who makes the best jollof.' },
];
