// Copies the web game (../danfo-driver) into www/ for Capacitor.
//   node scripts/build-web.mjs            -> development build: Google TEST ads
//   node scripts/build-web.mjs --release  -> release build: real AdMob ad units
// RevenueCat keys are read from keys.local.json (git-ignored) and written into www only.
import { cpSync, rmSync, mkdirSync, writeFileSync, existsSync, readFileSync } from 'node:fs';
import { buildSync } from 'esbuild';
import { join, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = join(dirname(fileURLToPath(import.meta.url)), '..'), src = join(root, '..', 'danfo-driver'), out = join(root, 'www');
const release = process.argv.includes('--release');
const skip = new Set(['screenshots', 'SUNO_BRIEF.md', 'quiz-sources.json', 'sw.js', 'README.md', 'RESEARCH.md', 'STORE_READY.md']);
rmSync(out, { recursive: true, force: true }); mkdirSync(out, { recursive: true });
cpSync(src, out, { recursive: true, filter: p => !skip.has(basename(p)) && !(p.endsWith('.md') && p !== src) });
let keys = {}; const kf = join(root, 'keys.local.json');
if (existsSync(kf)) keys = JSON.parse(readFileSync(kf, 'utf8'));
const real = k => typeof k === 'string' && /^(appl|goog)_/.test(k) ? k : '';
writeFileSync(join(out, 'monetize', 'build.js'), `// generated by scripts/build-web.mjs, do not edit or commit\nwindow.DC_BUILD = ${JSON.stringify({ mode: release ? 'release' : 'dev', revenuecatAppleKey: real(keys.revenuecatAppleKey), revenuecatGoogleKey: real(keys.revenuecatGoogleKey) })};\n`);
// native plugins (AdMob, RevenueCat, Share, App) bundled for the plain-JS game
buildSync({ entryPoints: [join(root, 'scripts', 'plugins-entry.js')], bundle: true, format: 'iife', minify: true, target: ['es2019'], outfile: join(out, 'monetize', 'plugins.js'), logLevel: 'warning' });
// load the build info + native plugins before the money config in the app's index.html
const ix = join(out, 'index.html'); writeFileSync(ix, readFileSync(ix, 'utf8').replace('<script src="monetize/config.js"></script>', '<script src="monetize/build.js"></script>\n<script src="monetize/plugins.js"></script>\n<script src="monetize/config.js"></script>'));
console.log(`www built (${release ? 'RELEASE: real ad units' : 'DEV: Google test ads'}). RevenueCat keys: apple ${real(keys.revenuecatAppleKey) ? 'set' : 'missing'}, google ${real(keys.revenuecatGoogleKey) ? 'set' : 'missing'}`);
